### ISSUE TITLE
other SOAP based services

### ISSUE THREAD

**Issue by sckott** [iobis/training#1]
Sorry for dropping in here, but thought I'd ping about related work. I saw @pieterprovoost `worms` R client. We have a client `taxizesoap` that works with worms, pesi and mycobank  https://github.com/ropensci/taxizesoap  - that focuses on taxonomy use cases  - these are not included in `taxize` as they use SOAP web services

**Comment by pieterprovoost** [comment]
Thanks Scott. I'm aware of `taxizesoap`, the `worms` package was a temporary solution because of https://github.com/ropensci/taxizesoap/issues/4

**Comment by sckott** [comment]
okay, `worms` looks nice, esp w/o having to use a SOAP client :)
