### ISSUE TITLE
How to fill Occurence Core for the polygonal spatial data?

### ISSUE THREAD

**Issue by Unscarrred** [iobis/training#4]
For example I have a data set like this:
![phyllophora](https://cloud.githubusercontent.com/assets/17651758/13919472/50572202-ef76-11e5-9829-c6e61e1e0ee3.jpg)

I can extract the ccordinates of each vertex for polygonal objects. Is it possible to publish such a data? If yes then how?

**Comment by pieterprovoost** [comment]
Yes, you can add the shape as WKT (https://en.wikipedia.org/wiki/Well-known_text) in the `footprintWKT` field. But please also complete `decimalLongitude`, `decimalLatitude` and `coordinateUncertaintyInMeters` with the centroid coordinates and radius and the radius around that centroid. How you can generate WKT will depend on your GIS.

**Comment by Unscarrred** [comment]
Many thanx, Pieter! We will try.
